import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  container: {
    padding: 16,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#F8F9FA",
    borderRadius: 12,
    elevation: 4,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
  },
  title: {
    fontSize: 22,
    fontWeight: "bold",
    marginBottom: 16,
    color: "#333",
    fontFamily: "PoppinsBold",
  },
  goalContainer: {
    width: "100%",
    marginTop: 16,
    marginBottom: 8,
  },
  progressBarContainer: {
    height: 8,
    backgroundColor: "#E0E0E0",
    borderRadius: 4,
    overflow: "hidden",
  },
  progressBar: {
    height: "100%",
    backgroundColor: "#4A90E2",
  },
  goalText: {
    fontSize: 14,
    color: "#666",
    marginTop: 4,
    fontFamily: "PoppinsBold",
    textAlign: "right",
  },
  milestoneContainer: {
    backgroundColor: "#EBF5FF",
    paddingVertical: 8,
    paddingHorizontal: 12,
    borderRadius: 20,
    marginVertical: 12,
  },
  milestoneText: {
    fontSize: 16,
    color: "#4A90E2",
    fontWeight: "bold",
    fontFamily: "PoppinsBold",
  },
  buttonContainer: {
    flexDirection: "row",
    marginVertical: 16,
  },
  button: {
    paddingVertical: 12,
    paddingHorizontal: 24,
    borderRadius: 30,
    marginHorizontal: 10,
    elevation: 2,
    fontFamily: "PoppinsBold",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.2,
    shadowRadius: 1.5,
  },
  decrementButton: {
    backgroundColor: "#FF6B6B",
  },
  incrementButton: {
    backgroundColor: "#4A90E2",
  },
  buttonText: {
    color: "white",
    fontSize: 24,
    fontWeight: "bold",
  },
  graphTitle: {
    fontSize: 18,
    fontFamily: "PoppinsBold",
    fontWeight: "bold",
    marginTop: 16,
    marginBottom: 8,
    color: "#333",
    alignSelf: "flex-start",
  },
  chartContainer: {
    marginTop: 4,
    marginBottom: 16,
    borderRadius: 16,
    overflow: "hidden",
    backgroundColor: "white",
    padding: 8,
    elevation: 2,
  },
  chart: {
    borderRadius: 16,
  },
  tipsContainer: {
    width: "100%",
    backgroundColor: "#E6F2FF",
    borderRadius: 8,
    padding: 16,
    marginTop: 8,
  },
  tipHeader: {
    flexDirection: "row",
    fontFamily: "PoppinsBold",
    alignItems: "center",
    marginBottom: 8,
  },
  tipTitle: {
    fontSize: 16,
    fontWeight: "bold",
    fontFamily: "PoppinsBold",
    color: "#4A90E2",
    marginLeft: 8,
  },
  tipText: {
    fontSize: 15,
    fontFamily: "PoppinsRegular",
    color: "#555",
    lineHeight: 20,
  },
});
